# Generated by Django 4.2.4 on 2023-09-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='cycle',
            field=models.CharField(default='True', max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering',
            field=models.CharField(default='True', max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
