# Generated by Django 4.2.4 on 2023-09-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0004_plantdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdetail',
            name='fruiting_season',
            field=models.JSONField(max_length=255, null=True),
        ),
    ]
