# Generated by Django 4.2.4 on 2023-09-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0005_alter_plantdetail_fruiting_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdetail',
            name='fruiting_season',
        ),
    ]
