# Generated by Django 4.2.4 on 2023-09-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0006_remove_plantdetail_fruiting_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdetail',
            name='rare',
        ),
        migrations.AddField(
            model_name='plantdetail',
            name='fruiting_season',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
