# Generated by Django 4.2.4 on 2023-09-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0007_remove_plantdetail_rare_plantdetail_fruiting_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdetail',
            name='fruiting_season',
        ),
    ]
