# Generated by Django 4.2.4 on 2023-09-08 15:33

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0008_remove_plantdetail_fruiting_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='sunlight',
            field=models.JSONField(max_length=30, null=True, verbose_name=django.db.models.fields.CharField),
        ),
        migrations.AddField(
            model_name='plantdetail',
            name='rare',
            field=models.BooleanField(null=True),
        ),
    ]
