# Generated by Django 4.2.4 on 2023-09-09 05:28

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0013_alter_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdetail',
            name='attracts',
            field=models.JSONField(max_length=255, null=True, verbose_name=django.db.models.fields.CharField),
        ),
        migrations.AddField(
            model_name='plantdetail',
            name='fruiting_season',
            field=models.JSONField(max_length=255, null=True, verbose_name=django.db.models.fields.CharField),
        ),
    ]
