# Generated by Django 4.2.4 on 2023-09-09 09:48

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0015_alter_plant_cycle_alter_plant_image_alter_plant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='cycle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.JSONField(max_length=30, null=True, verbose_name=django.db.models.fields.CharField),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='attracts',
            field=models.JSONField(max_length=255, null=True, verbose_name=django.db.models.fields.CharField),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='care_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='cycle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='edible_fruit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='flowering_season',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='flowers',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='fruit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='fruiting_season',
            field=models.JSONField(max_length=255, null=True, verbose_name=django.db.models.fields.CharField),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='growth_rate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='indoor',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='maintenance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='medicinal',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='poisonous_to_humans',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='poisonous_to_pets',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='rare',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='thorny',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='watering',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
