# Generated by Django 4.2.4 on 2023-09-09 12:30

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0016_alter_plant_cycle_alter_plant_image_alter_plant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdetail',
            name='fruiting_season',
        ),
        migrations.RemoveField(
            model_name='plantdetail',
            name='rare',
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.JSONField(max_length=2048, null=True, verbose_name=django.db.models.fields.CharField),
        ),
        migrations.AlterField(
            model_name='plantdetail',
            name='image',
            field=models.JSONField(max_length=2048, null=True, verbose_name=django.db.models.fields.CharField),
        ),
    ]
