# Generated by Django 4.2.4 on 2023-10-03 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiPlantHub', '0019_user_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='save_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
