# Generated by Django 4.2.4 on 2023-10-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0020_plant_like_plant_save_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='like',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='save',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiPlantHub.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiPlantHub.user')),
            ],
        ),
    ]
