# Generated by Django 4.2.4 on 2023-10-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0021_remove_plant_like_remove_plant_save_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
