# Generated by Django 4.2.4 on 2023-10-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0022_remove_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
