# Generated by Django 4.2.4 on 2023-10-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0024_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_likes', to='apiPlantHub.plant'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='apiPlantHub.userprofile'),
        ),
    ]
