# Generated by Django 4.2.4 on 2023-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0027_userprofile_id_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='', max_length=25, primary_key=True, serialize=False),
        ),
    ]
