# Generated by Django 4.2.4 on 2023-10-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0028_alter_userprofile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id',
            new_name='uid',
        ),
    ]
