# Generated by Django 4.2.4 on 2023-10-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlantHub', '0029_rename_id_userprofile_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uid',
            new_name='id',
        ),
    ]
